// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv6YIh3ndyGZiy9zAx5tkP7p9sK6cvOzg',
    appId: '1:246016032495:web:5b27df4d19c8d8d66f651a',
    messagingSenderId: '246016032495',
    projectId: 'jajanyuk-92657',
    authDomain: 'jajanyuk-92657.firebaseapp.com',
    storageBucket: 'jajanyuk-92657.firebasestorage.app',
    measurementId: 'G-FWXPFN9NYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaz8WnTRvaXh9HPUOGVDnErlw6sb3Al_g',
    appId: '1:246016032495:android:40fe4a1dbd07d68f6f651a',
    messagingSenderId: '246016032495',
    projectId: 'jajanyuk-92657',
    storageBucket: 'jajanyuk-92657.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdOvOarkgOuKDneApO7gR7oTGwFravwn0',
    appId: '1:246016032495:ios:479bfe3fac7ab8296f651a',
    messagingSenderId: '246016032495',
    projectId: 'jajanyuk-92657',
    storageBucket: 'jajanyuk-92657.firebasestorage.app',
    iosBundleId: 'com.example.jajanyuk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdOvOarkgOuKDneApO7gR7oTGwFravwn0',
    appId: '1:246016032495:ios:479bfe3fac7ab8296f651a',
    messagingSenderId: '246016032495',
    projectId: 'jajanyuk-92657',
    storageBucket: 'jajanyuk-92657.firebasestorage.app',
    iosBundleId: 'com.example.jajanyuk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv6YIh3ndyGZiy9zAx5tkP7p9sK6cvOzg',
    appId: '1:246016032495:web:19e985d0c9e98f546f651a',
    messagingSenderId: '246016032495',
    projectId: 'jajanyuk-92657',
    authDomain: 'jajanyuk-92657.firebaseapp.com',
    storageBucket: 'jajanyuk-92657.firebasestorage.app',
    measurementId: 'G-MR0J9DPD82',
  );
}
